name: OSX
on:
  push:
    paths-ignore:
    - 'docs/**'
    - 'README.md'
    - '.readthedocs.yaml'

jobs:
  Test:
    runs-on: macos-latest
    env:
      PYTHON_VERSION: 3.6
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v2
        # Miniconda is used since it is compiled against MACOSX 10.9
        with:
          auto-update-conda: true
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install build dependencies
        run: |
          conda install cffi
          conda install -c conda-forge pcpp
        shell: bash -l {0} # This activates conda/test env

      - name: Build the library, the package and the examples
        run: |
          export MACOSX_DEPLOYMENT_TARGET=10.9
          make CC=gcc-9
          make package CC=gcc-9 PYTHON=python${PYTHON_VERSION}
          make examples CC=gcc-9
        shell: bash -l {0}

      - name: Run the examples
        run: |
          ./bin/example-forward
          ./bin/example-backward

      - name: Install runtime dependencies
        run: |
          conda install cffi numpy      # Package dependencies
          conda install coverage pytest # Tests dependencies
        shell: bash -l {0}

      - name: Test with pytest
        run: |
          PYTHON=python${PYTHON_VERSION} ./tests/run.sh
        shell: bash -l {0}

      - name: Check PyPI
        run: |
          echo "UPDATE_PYPI=$(./dist/update-pypi.py)" >> $GITHUB_ENV

      - name: Install dist dependencies
        if: env.UPDATE_PYPI == 'True'
        run: |
          conda install wheel
        shell: bash -l {0}

      - name: Build wheel
        if: env.UPDATE_PYPI == 'True'
        run: |
          CC=gcc-9 PYTHON=python${PYTHON_VERSION} ./dist/build-wheel.sh
        shell: bash -l {0}

      - uses: actions/upload-artifact@v2
        if: env.UPDATE_PYPI == 'True'
        with:
          name: temporary-wheels
          path: |
            dist/wheels/*.whl
          retention-days: 1

  Publish:
    needs: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check PyPI
        run: |
          echo "UPDATE_PYPI=$(./dist/update-pypi.py --system=Darwin)" >> $GITHUB_ENV

      - uses: actions/download-artifact@v2
        if: env.UPDATE_PYPI == 'True'
        with:
          name: temporary-wheels
          path: dist/wheels

      - name: Upload to PyPI
        if: env.UPDATE_PYPI == 'True'
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          packages_dir: dist/wheels

  Clean:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [Publish, Test]

    steps:
      - uses: geekyeggo/delete-artifact@v1
        with:
          name: temporary-wheels
